---
# ============================================================
#  Cluster-wide variables
# ============================================================

# Kubernetes
k8s_version: "1.32"
pod_cidr:    "10.244.0.0/16"
master_ip:   "192.168.56.10"

# Calico CNI
calico_version: "v3.29.1"

# MetalLB
metallb_version: "0.14.9"
metallb_ip_range: "192.168.56.200-192.168.56.250"

# NGINX Ingress
nginx_ingress_version: "4.11.3"

# ArgoCD
argocd_version: "v2.13.3"

# Online Boutique (Google microservices-demo)
boutique_version: "HEAD"

# Monitoring (kube-prometheus-stack)
# Chart version is auto-resolved at deploy time via helm search repo
grafana_admin_password: "grafana"
