---
# ============================================================
#  Cluster-wide variables
# ============================================================

# Kubernetes
k8s_version: "1.32"
pod_cidr:    "10.244.0.0/16"
master_ip:   "192.168.56.10"

# Calico CNI
calico_version: "v3.29.1"
